### ISSUE TITLE
[E::hk_sd_ploidy_XY] multiple chr contain 'X' or 'Y' in names

### ISSUE THREAD

**Issue by zcq23** [zhang-jiankun/LiMCA#1]
Hi, I met a problem that use your rawdata SRR25505058 with"$ hickit -i ${OUTPUT}/structure/SRR25505058.impute.pairs_with_chromsize.gz -Sr1m -c1 -r10m -c2 -b4m  -o out.pairs
[M::hk_map_read] read 694017 pairs
[E::hk_sd_ploidy_XY] multiple chr contain 'X' or 'Y' in names"

my hickit's version is r291

head -n 50 SRR25505058.impute.pairs_with_chromsize.gz：
$ zcat filtered_pairs_with_chromsize.gz | head -n 50
pairs format v1.0
#sorted: chr1-chr2-pos1-pos2
#shape: upper triangle
#chromsize: 1 197195432
#chromsize: 2 181748087
#chromsize: 3 159599783
#chromsize: 4 155630120
#chromsize: 5 152537259
#chromsize: 6 149517037
#chromsize: 7 152524553
#chromsize: 8 131738871
#chromsize: 9 124076172
#chromsize: 10 129993255
#chromsize: 11 121843856
#chromsize: 12 121257530
#chromsize: 13 120284312
#chromsize: 14 125194864
#chromsize: 15 103494974
#chromsize: 16 98319150
#chromsize: 17 95272651
#chromsize: 18 90772031
#chromsize: 19 61342430
#chromsize: X 166650296
#columns: readID chr1 pos1 chr2 pos2 strand1 strand2 phase0 phase1 phase_prob00 phase_prob01 phase_prob10 phase_prob11
. chr1 3003625 chr1 7400077 + + . . 0.836 0.008 0.002 0.154
. chr1 3009032 chr1 7403384 + + . . 0.839 0.008 0.002 0.151
. chr1 3012303 chr1 4114735 + + 1 1 0.000 0.000 0.000 1.000
. chr1 3018787 chr1 61903331 + + 1 . 0.000 0.000 0.004 0.996

tail -n 50 SRR25505058.impute.pairs_with_chromsize.gz：
. chrX 169912765 chrX 169915788 + + 1 1 0.000 0.000 0.000 1.000
. chrX 170813085 chrX 170857943 + + 1 1 0.000 0.000 0.000 1.000
. chrX 31780402 chrY 4021769 + + 1 0 0.000 0.000 1.000 0.000
. chrX 100513028 chrY 9488953 + + 1 0 0.000 0.000 1.000 0.000
. chrX 120299636 chrY 2161589 + + 1 0 0.000 0.000 1.000 0.000
. chrX 142046394 chrY 2161622 + + 1 0 0.000 0.000 1.000 0.000
. chrX 143483022 chrY 4156800 + + 1 0 0.000 0.000 1.000 0.000
. chrX 143483028 chrY 4150242 + + 1 0 0.000 0.000 1.000 0.000
. chrY 142402 chrY 262227 + + 0 0 1.000 0.000 0.000 0.000
. chrY 258185 chrY 259206 + + 0 0 1.000 0.000 0.000 0.000
. chrY 259786 chrY 22211175 + + 0 0 1.000 0.000 0.000 0.000
. chrY 671941 chrY 768654 + + 0 0 1.000 0.000 0.000 0.000
. chrY 700407 chrY 737511 + + 0 0 1.000 0.000 0.000 0.000
. chrY 728659 chrY 89651070 + + 0 0 1.000 0.000 0.000 0.000
. chrY 732343 chrY 765350 + + 0 0 1.000 0.000 0.000 0.000
. chrY 764219 chrY 767145 + + 0 0 1.000 0.000 0.000 0.000
Thanks and hope for your reply!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by zhang-jiankun** [comment]
Hi @zcq23,

Thank you for your interest. This issue may be caused by the chromosomes names in the imputed .pairs header lacking the "chr" prefix, which should be **"#chromsize: chrX 166650296".**

In addition, the olfactory cells are all from male mice. It looks like there are interactions from chrY in the file, but the chrY line (**"#chromsize: chrY 91744698"**) is missing in the .pairs header. 

I hope this will help.

**Comment by zcq23** [comment]
> Hi @zcq23,
> 
> Thank you for your interest. This issue may be caused by the chromosomes names in the imputed .pairs header lacking the "chr" prefix, which should be **"#chromsize: chrX 166650296".**
> 
> In addition, the olfactory cells are all from male mice. It looks like there are interactions from chrY in the file, but the chrY line (**"#chromsize: chrY 91744698"**) is missing in the .pairs header.
> 
> I hope this will help.

ohhhhhhhhhh I see! Thank you so much for your reply!!!!!!!!!!!!!!!!! It will be very helpful to me! Thank you again for your reply and advice, I will go ahead and make the changes and try some more. Thank you very much!!! 🌹🌹🌹🌹🌹

**Comment by zcq23** [comment]
Sorry please forgive me to reopen this problem again😭😭😭I met a bug "hickit: bin.c:70: hk_bmap_pos2bid: Assertion `pos < m->beads[hi].en' failed." in code: hickit -s${rep} -i ${OUTPUT}/structure/SRR25505065.impute.pairs_with_chromsize.gz -Sr1m -c1 -r10m -c2 -b4m \

To test which step was wrong, I run them step by step:
hickit -i ${OUTPUT}/structure/SRR25505065.impute.pairs_with_chromsize.gz -Sr1m -c1 -o out.pairs √
hickit -i out.pairs -r10m -c2 -o out2.pairs √
hickit -i out2.pairs -b4m -o out3.pairs ×
and I met the bug "hickit: bin.c:70: hk_bmap_pos2bid: Assertion `pos < m->beads[hi].en' failed." in the last one, it is so strange!
my SRR25505065.impute.pairs_with_chromsize.gz is:

pairs format v1.0
#sorted: chr1-chr2-pos1-pos2
#shape: upper triangle
#chromsize: chr1 197195432
#chromsize: chr2 181748087
#chromsize: chr3 159599783
#chromsize: chr4 155630120
#chromsize: chr5 152537259
#chromsize: chr6 149517037
#chromsize: chr7 152524553
#chromsize: chr8 131738871
#chromsize: chr9 124076172
#chromsize: chr10 129993255
#chromsize: chr11 121843856
#chromsize: chr12 121257530
#chromsize: chr13 120284312
#chromsize: chr14 125194864
#chromsize: chr15 103494974
#chromsize: chr16 98319150
#chromsize: chr17 95272651
#chromsize: chr18 90772031
#chromsize: chr19 61342430
#chromsize: chrX 166650296
#chromsize: chrY 91744698
#columns: readID chr1 pos1 chr2 pos2 strand1 strand2 phase0 phase1 phase_prob00 phase_prob01 phase_prob10 phase_prob11
. chr1 3016884 chr1 52750084 + + 0 1 0.000 1.000 0.000 0.000
. chr1 3023157 chr1 3557230 + + 0 0 1.000 0.000 0.000 0.000
. chr1 3028456 chr1 3177837 + + 1 1 0.000 0.000 0.000 1.000
. chr1 3033910 chr1 92724777 + + 1 . 0.000 0.000 0.122 0.878
. chrX 169915040 chrY 90809054 + + 1 0 0.000 0.000 1.000 0.000
. chrX 170005138 chrY 90805145 + + 1 0 0.000 0.000 1.000 0.000

I run hickit.js chronly - | hickit.js bedflt ${PAR} - |, hickit.js sam2seg -v and hickit -u all before. The last sucessful output file "out2.pairs" is:

pairs format v1.0
#sorted: chr1-chr2-pos1-pos2
#shape: upper triangle
#chromosome: chr1a 197195432
#chromosome: chr1b 197195432
#chromosome: chr2a 181748087
#chromosome: chr2b 181748087
#chromosome: chr3a 159599783
#chromosome: chr3b 159599783
#chromosome: chr4a 155630120
#chromosome: chr4b 155630120
#chromosome: chr5a 152537259
#chromosome: chr5b 152537259
#chromosome: chr6a 149517037
#chromosome: chr6b 149517037
#chromosome: chr7a 152524553
#chromosome: chr7b 152524553
#chromosome: chr8a 131738871
#chromosome: chr8b 131738871
#chromosome: chr9a 124076172
#chromosome: chr9b 124076172
#chromosome: chr10a 129993255
#chromosome: chr10b 129993255
#chromosome: chr11a 121843856
#chromosome: chr11b 121843856
#chromosome: chr12a 121257530
#chromosome: chr12b 121257530
#chromosome: chr13a 120284312
#chromosome: chr13b 120284312
#chromosome: chr14a 125194864
#chromosome: chr14b 125194864
#chromosome: chr15a 103494974
#chromosome: chr15b 103494974
#chromosome: chr16a 98319150
#chromosome: chr16b 98319150
#chromosome: chr17a 95272651
#chromosome: chr17b 95272651
#chromosome: chr18a 90772031
#chromosome: chr18b 90772031
#chromosome: chr19a 61342430
#chromosome: chr19b 61342430
#chromosome: chrX 166650296
#chromosome: chrY 91744698
#columns: readID chr1 pos1 chr2 pos2 strand1 strand2 n_neighbors n_nei_corner
. chr1a 3023157 chr1a 3557230 + + 279 5
. chr1a 3160608 chr1a 3164536 + + 275 0
. chr1a 3164578 chr1a 3166318 + + 275 0
. chrX 169941413 chrX 169942569 + + 439 0
. chrY 726435 chrY 737250 + + 17 0

Would you please take a look for me? Thank you very much again!!!!!!!!!! Looking forward to your reply😭

**Comment by zhang-jiankun** [comment]
If you are trying to reconstruct the 3D genome structures, you should use "-O out.3dg" instead of "-o out.pairs", because "-b4m" is an option for 3D modeling.

**Comment by zcq23** [comment]
> If you are trying to reconstruct the 3D genome structures, you should use "-O out.3dg" instead of "-o out.pairs", because "-b4m" is an option for 3D modeling.

yes I immediately changed my code but still met it : 
$ hickit -i out2.pairs -b4m -O out.3dg
[M::hk_map_read] read 260357 pairs
[M::hk_pair_filter_close_legs] filtered out 0/260357 pairs with close legs
[M::hk_pair_dedup] duplicate rate: 0.00% = 0 / 260357
[M::hk_bmap_gen] generated 1297 beads
hickit: bin.c:70: hk_bmap_pos2bid: Assertion `pos < m->beads[hi].en' failed.
Aborted (core dumped)

and when I run the all: 
$ hickit -i ${OUTPUT}/structure/SRR25505065.impute.pairs_with_chromsize.gz -Sr1m -c1 -r10m -c2 -b4m -O out.3dg
hickit: main.c:103: main: Assertion `m' failed.
Aborted (core dumped)

Does it mean something wrong in my input file? Thank you very very much!

**Comment by zhang-jiankun** [comment]
Could you attach your updated SRR25505065.impute.pairs_with_chromsize.gz file? For reconstruction, just use SRR25505065.impute.pairs_with_chromsize.gz and don't need to generate out2.pairs.

**Comment by zcq23** [comment]
> Could you attach your updated SRR25505065.impute.pairs_with_chromsize.gz file? For reconstruction, just use SRR25505065.impute.pairs_with_chromsize.gz and don't need to generate out2.pairs.

yes my SRR25505065.impute.pairs_with_chromsize.gz is 
[Uploading SRR25505065.impute.pairs_with_chromsize.gz…]()

**Comment by zcq23** [comment]
> Could you attach your updated SRR25505065.impute.pairs_with_chromsize.gz file? For reconstruction, just use SRR25505065.impute.pairs_with_chromsize.gz and don't need to generate out2.pairs.

yes my SRR25505065.impute.pairs_with_chromsize.gz is：https://cloud.tsinghua.edu.cn/f/d8f3839597394be29788/?dl=1
the chromsize was attached in the SRR25505065.impute.pairs.gz directly by 

input_file="${OUTPUT}/structure/SRR25505065.impute.pairs.gz"
output_file="${OUTPUT}/structure/SRR25505065.impute.pairs_with_chromsize.gz"

chromsize_info=$(cat <<EOF
#chromsize: chr1 197195432
#chromsize: chr2 181748087
#chromsize: chr3 159599783
#chromsize: chr4 155630120
#chromsize: chr5 152537259
#chromsize: chr6 149517037
#chromsize: chr7 152524553
#chromsize: chr8 131738871
#chromsize: chr9 124076172
#chromsize: chr10 129993255
#chromsize: chr11 121843856
#chromsize: chr12 121257530
#chromsize: chr13 120284312
#chromsize: chr14 125194864
#chromsize: chr15 103494974
#chromsize: chr16 98319150
#chromsize: chr17 95272651
#chromsize: chr18 90772031
#chromsize: chr19 61342430
#chromsize: chrX 166650296
#chromsize: chrY 91744698
EOF
)

zcat "$input_file" | awk -v chromsize_info="$chromsize_info" '
/^#shape: upper triangle$/ {
    print
    print chromsize_info
    next
}
{ print }
' | gzip > "$output_file"

I don't know whether it will influence the raw file😭so sorry to trouble you

**Comment by zhang-jiankun** [comment]
It seems that the chromsize lines do not match the reference genome you actually used. You can check the out-of-bound pairs by running `less SRR25505065.impute.pairs_with_chromsize.gz  | awk '($4=="chr2" && $5>181748087)' | head`.

I strongly recommend that you follow the [typical Dip-C workflow](https://github.com/tanlongzhi/dip-c?tab=readme-ov-file#workflow) step by step so that you wouldn't run into these issues.

**Comment by zcq23** [comment]
> It seems that the chromsize lines do not match the reference genome you actually used. You can check the out-of-bound pairs by running `less SRR25505065.impute.pairs_with_chromsize.gz | awk '($4=="chr2" && $5>181748087)' | head`.
> 
> I strongly recommend that you follow the [typical Dip-C workflow](https://github.com/tanlongzhi/dip-c?tab=readme-ov-file#workflow) step by step so that you wouldn't run into these issues.

ohhhhh on this way! yes sir I will go and check and make the necessary changes according to your suggestion, and follow the typical Dip-C workflow step by step💪
Thank you very much for your reply and advice, which has been so helpful to me! Sincerely hope you have a nice day! 😊☀☀☀

**Comment by zcq23** [comment]
Okayyyyyyyyyyyyyyyyyy!!!


-----原始邮件-----
发件人:Jiankun_Zhang ***@***.***>
发送时间:2024-08-14 11:58:47 (星期三)
收件人: zhang-jiankun/LiMCA ***@***.***>
抄送: "Zheng Changqing" ***@***.***>, "State change" ***@***.***>
主题: Re: [zhang-jiankun/LiMCA] [E::hk_sd_ploidy_XY] multiple chr contain 'X' or 'Y' in names (Issue #1)






Closed #1 as completed.
