### ISSUE TITLE
merge .allValidPairs of the same celltype cells to reconstruct 3D model and the strain of mouse

### ISSUE THREAD

**Issue by zcq23** [zhang-jiankun/LiMCA#2]
Hi @zhang-jiankun, my 3D model aligning between rep1-3 of the single cell sample "SRR25585058_20Kb_1-3.clean.3dg" is:
[M::align] median deviation between file 0 and file 1: 0.11901128445530633
[M::align] median deviation between file 0 and file 2: 0.10202856767681674
[M::align] median deviation between file 1 and file 2: 0.30208532515466541

but when I compare the cell with another single cell "SRR25585060_20Kb_1-3.clean.3dg"(which as SRR25585058_20Kb_4-6.clean.3dg, they are the same celltype), the RMSD are:
[M::align] median deviation between file 0 and file 3: 24.71208459362338
[M::align] median deviation between file 0 and file 4: 24.71182519219675
[M::align] median deviation between file 0 and file 5: 24.70092361301726

I wonder whether I can merge them to reconstruct 3D model to remove the difference between cells, so I can compare their structure differences causing by celltype rather than cell individual.

and the above data were dba×c57, when it comes to cast×c57, is:
[M::align] median deviation between file 0 and file 1: 7.31823227353984
[M::align] median deviation between file 0 and file 2: 3.55399932554033

[M::align] median deviation between file 0 and file 3: 15.3503609551515
[M::align] median deviation between file 0 and file 4: 18.2527622659593
[M::align] median deviation between file 0 and file 5: 18.6954653468358

why the different strain will influence the reconstruct model a lot, it is so strange😭

thanks in advance and hope for your reply!!!

**Comment by zhang-jiankun** [comment]
To do so, you need to merge all single-cell pairs and then perform 3D reconstruction and alignment.

I think that Chai et al. did similar things in their recent preprint, where they merged similar cells into metacells and reconstructed the 3D genome structures of metacells (see Fig. 1F https://www.biorxiv.org/node/3814554.abstract). This seems like an interestring idea to explore but the analysis methods might require some adjustments. You could also try calling significant interactions with FitHi-C and then use those filtered interactions as input for 3D reconstructions.

**Comment by zhang-jiankun** [comment]
Another critical thing is the resolution. Different cells have distinct 3D structures. In doing so, you merge chromatin pairs from different cells. There could be numerous conflicting contacts, which might limit the resolution. I think a resolution of 20 kb may be too high for this analysis.

It's an effective way to use only significant interactions but we need to pay closer attention to inter-chromosomal contacts.

**Comment by zcq23** [comment]
> Another critical thing is the resolution. Different cells have distinct 3D structures. In doing so, you merge chromatin pairs from different cells. There could be numerous conflicting contacts, which might limit the resolution. I think a resolution of 20 kb may be too high for this analysis.
> 
> It's an effective way to use only significant interactions but we need to pay closer attention to inter-chromosomal contacts.

oh sooooooooooooooooo appreciated for your reply!!! I will take more care of it and try the methods as you mentioned above, and thanks again for your reply and suggestions sincerely! Have a nice day☀☀☀!!!
