### ISSUE TITLE
Ensemble LiMCA data compare with bulk Hi-C 

### ISSUE THREAD

**Issue by zcq23** [zhang-jiankun/LiMCA#3]
Hi jiankun, I try to merge different number of cells in article dataset to compare with bulk Hi-C for testing, after calculating the first eigen value of A/B compartment  at 100-kb resolution, my correlation between random selected 200 cells and GSE63525_GM12878_insitu_primary_30_100kb.cool in Rao et.al 2014 is 0.79.
I wonder if the using bulk Hi-C is different with you so the result doesn't meet the 0.95 in Fig. 1c😭hope for your reply and many many many thanks !!!

**Comment by zhang-jiankun** [comment]
Hi @zcq23 ,

The figure legend of Fig. 1c is incorrect; it should read 500kb, not 100kb. Apologies for the confusion. The descriptions in the Methods section is correct.

" We **used the cooltools eigs-cis function (https://github. com/open2c/cooltools) to calculate A/B compartments at a 500-kb resolution** and the cooltools insulation function to calculate insulation scores at a 100-kb resolution with a 1-Mb window. "

**Comment by zcq23** [comment]
> Hi @zcq23 ,
> 
> The figure legend of Fig. 1c is incorrect; it should read 500kb, not 100kb. Apologies for the confusion. The descriptions in the Methods section is correct.
> 
> " We **used the cooltools eigs-cis function (https://github. com/open2c/cooltools) to calculate A/B compartments at a 500-kb resolution** and the cooltools insulation function to calculate insulation scores at a 100-kb resolution with a 1-Mb window. "

ohhhhhhhhh I see! Thanks very very much for your reply!!!
