### ISSUE TITLE
I got a strange "Sequence Length Distribution" after pre-meta 

### ISSUE THREAD

**Issue by zcq23** [zhang-jiankun/LiMCA#4]
Hi, when I run the code " /data1/seqtk/seqtk mergepe ${PREFIX}_1.fq.gz ${PREFIX}_2.fq.gz | /data1/pre-pe-master/pre-meta - > ${PREFIX}.fastq 2> ${PREFIX}.log" and "fastqc -t 30 *.fastq -o" after, compared to my control data downloaded from GEO, I found that my "Sequence Length Distribution" had a new short peak and may be the peak cause the next unmapping reads strikely increase😭. It's like this:
![image](https://github.com/user-attachments/assets/10f82809-c657-48d8-83b4-e1b632a5d2a5)

compared to the control:
![image](https://github.com/user-attachments/assets/1ce37b96-ec03-4e33-b0c2-44bd32d9e511)

It's so strange and my mapping rate has dropped from 26 to 5, which makes many information loss😭. Can you help me? many many many thanks!!!!!!!!!!!

**Comment by zhang-jiankun** [comment]
Could you please clarify what this data is? Is this LiMCA or Dip-C data? Besides, what does "control" mean?

**Comment by zcq23** [comment]
> Could you please clarify what this data is? Is this LiMCA or Dip-C data? Besides, what does "control" mean?

It's LiMCA data obtained through LiMCA pipeline described in article on mESCs, and it's the third test on meta enzyme for its optimum concentration (because the batches of enzyme are also different), and "control" mean the result of normal first two times and the data downloaded from article offered SRR25505180. 
In this third test our main peak of the library is about 320bp, which is shorter than the previous two test, so we wonder whether the library were too small caused the reads after trim to be too short for normal mapping. But local alignment is not particularly limited by fragment length, so we don't know what went wrong to cause so many unmapping😭. Could you take a look at that for us? many many many thanks!!!

**Comment by zhang-jiankun** [comment]
I think this is primarility an experimental issue, especially concerning the quality of META transposon you used. You've already contacted Honggui, and he could help you with this. I don't have expertise in wet lab. Thank you for your understanding.

**Comment by zcq23** [comment]
> I think this is primarility an experimental issue, especially concerning the quality of META transposon you used. You've already contacted Honggui, and he could help you with this. I don't have expertise in wet lab. Thank you for your understanding.

ohhhhhhhhhh I see! I will check the quality of META transposon we used as you suggested and keep going! Thanks for your prompt reply and warm help, thank you very very sincerely and hope you have a good mood as sunny as today! 😊☀☀
